pages:
  stage: deploy
  script:
    - mv build/hover-blast/{hover-blast,index}.html
    - cp src/resources/Ship.png build/hover-blast
  artifacts:
    paths:
      - build/hover-blast
  publish: build/hover-blast
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  
